version: '3'

networks:
  micro-net:
    driver: overlay

services:

  caddy:
    image: varadsat/micro-caddy:1.0.1
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - micro-net

  front-end:
    image: varadsat/front-end:1.0.2
    deploy:
      mode: replicated
      replicas: 1
    environment:
      BROKER_URL: http://backend
    networks:
      - micro-net

  broker-service:
    image: varadsat/broker-service:1.0.2
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - micro-net

  listener-service:
    image: varadsat/listener-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - micro-net

  authentication-service:
    image: varadsat/authentication-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
    networks:
      - micro-net

  logger-service:
    image: varadsat/logger-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - micro-net

  mail-service:
    image: varadsat/mail-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: none
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      FROM_NAME: "John Smith"
      FROM_ADDRESS: john.smith@example.com
    networks:
      - micro-net

  rabbitmq:
    image: 'rabbitmq:4.2.2-alpine'
    deploy:
      mode: global
    networks:
      - micro-net

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "8025:8025"
    deploy:
      mode: global
    networks:
      - micro-net

  mongo-db:
    image: 'mongo:4.2.17-bionic'
    ports:
      - "27017:27017"
    deploy:
      mode: global
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db
    networks:
      - micro-net

  postgres:
    image: 'postgres:16.11'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    networks:
      - micro-net

volumes:
  caddy_data:
    external: true
  caddy_config: